### ISSUE TITLE
Customization on bootstrap-selectsplitter

### ISSUE THREAD

**Issue by fonylew** [xavierfaucon/bootstrap-selectsplitter#2]
This is exactly what I want.
My data is two level select that is exactly this component does.

But, It looks so simple and can't be applied any style to it.
It always appears in two vertical boxes, not in two columns. Even, I added either col-md-6 or col-lg-6 in javascript file.
Beside, I found that this plug-in http://rickardn.github.io/listgroup.js/ would make it looked better.
So I add class='list-group' inside your javascript.
Unfortunately, it's still not working.

I would appreciate if you kindly provide more way to customize your wonderful component here. :+1: 
Cheers.

**Comment by X13454** [comment]
Hello,

I doubt I can improve the styling of select tags cross browser without heavy changes, so I prefer to keep the default behavior (Look at bootstrap selects --> they are also very lightly styled).

Unless I missed something, the plugin that you linked does not provide the ability to scroll down ; which is necessary and essential for selectsplitter :-).

For your problem for the two vertical boxes could you provide me a jsfiddle so that I see the problem?

Kind regards
